[package]
name = "abc430"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc430-a = { alias = "a", problem = "https://atcoder.jp/contests/abc430/tasks/abc430_a" }
abc430-b = { alias = "b", problem = "https://atcoder.jp/contests/abc430/tasks/abc430_b" }
abc430-c = { alias = "c", problem = "https://atcoder.jp/contests/abc430/tasks/abc430_c" }
abc430-d = { alias = "d", problem = "https://atcoder.jp/contests/abc430/tasks/abc430_d" }
abc430-e = { alias = "e", problem = "https://atcoder.jp/contests/abc430/tasks/abc430_e" }
abc430-f = { alias = "f", problem = "https://atcoder.jp/contests/abc430/tasks/abc430_f" }
abc430-g = { alias = "g", problem = "https://atcoder.jp/contests/abc430/tasks/abc430_g" }

[[bin]]
name = "abc430-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc430-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc430-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc430-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc430-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc430-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc430-g"
path = "src/bin/g.rs"

[dependencies]
rpds = "=1.1.1"
rand_xorshift = "=0.4.0"
rand_xoshiro = "=0.7.0"
statrs = "=0.18.0"
primal = "=0.3.3"
thiserror = "=2.0.16"
# 202301から:
ac-library-rs = "=0.2.0"
once_cell = "=1.21.3"
static_assertions = "=1.1.0"
varisat = "=0.2.2"
memoise = "=0.3.2"
argio = "=0.2.0"
bitvec = "=1.0.1"
counter = "=0.7.0"
hashbag = "=0.1.12"
pathfinding = "=4.14.0"
recur-fn = "=2.2.0"
indexing = { version = "=0.4.1", features = ["experimental_pointer_ranges"] }
amplify = { version = "=4.9.0", features = [
    "c_raw",
    "rand",
    "stringly_conversions",
] }
amplify_derive = "=4.0.1"
amplify_num = { version = "=0.5.3", features = ["std"] }
easy-ext = "=1.0.2"
multimap = "=0.10.1"
btreemultimap = "=0.1.1"
bstr = "=1.12.0"
az = "=1.2.1"
glidesort = "=0.1.2"
tap = "=1.0.1"
omniswap = "=0.1.0"
multiversion = "=0.8.0"
# 202004から続投:
num = "=0.4.3"
num-bigint = "=0.4.6"
num-complex = "=0.4.6"
num-integer = "=0.1.46"
num-iter = "=0.1.45"
num-rational = "=0.4.2"
num-traits = "=0.2.19"
num-derive = "=0.4.2"
ndarray = "=0.16.1"
nalgebra = "=0.34.0"
alga = "=0.9.3"
libm = "=0.2.15"
rand = "=0.9.2"
getrandom = "=0.3.3"
rand_chacha = "=0.9.0"
rand_core = "=0.9.3"
rand_hc = "=0.4.0"
rand_pcg = "=0.9.0"
rand_distr = "=0.5.1"
petgraph = "=0.8.2"
indexmap = "=2.11.0"
regex = "=1.11.2"
lazy_static = "=1.5.0"
ordered-float = "=5.0.0"
ascii = "=1.1.0"
permutohedron = "=0.2.4"
superslice = "=1.0.0"
itertools = "=0.14.0"
itertools-num = "=0.1.3"
maplit = "=1.0.2"
either = "=1.15.0"
im-rc = "=15.1.0"
fixedbitset = "=0.5.7"
bitset-fixed = "=0.1.0"
proconio = { version = "=0.5.0", features = ["derive"] }
text_io = "=0.1.13"
rustc-hash = "=2.1.1"
smallvec = { version = "=1.15.1", features = [
    "const_generics",
    "const_new",
    "write",
    "union",
    "serde",
    "arbitrary",
] }

[dev-dependencies]
